language: ruby
dist: xenial
cache: bundler

matrix:
  include:
    - rvm: 2.4
      gemfile: gems/rails5.gemfile
    - rvm: 2.5
      gemfile: gems/rails5.gemfile
    - rvm: 2.6
      gemfile: gems/rails5.gemfile
    - rvm: 2.6
      gemfile: gems/rails6.gemfile
    - rvm: 2.6
      gemfile: gems/rails5.gemfile
      env: COVERAGE=PartialSummary,Coveralls
    - rvm: truffleruby
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: ruby-head
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: jruby-head
