name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - 2.5
          - 2.6
          - 2.7
        
        experimental: [false]
        env:
          - BUNDLER_GEMFILE=gems/rails5.gemfile
          - BUNDLER_GEMFILE=gems/rails6.gemfile
        
        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
          - os: ubuntu
            ruby: jruby
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    
    - name: Installing packages (ubuntu)
      if: matrix.os == 'ubuntu'
      run: sudo apt-get install sqlite3 libsqlite3-dev
    
    - name: Installing packages (macos)
      if: matrix.os == 'macos'
      run: brew install sqlite3
    
    - name: Install dependencies
      run: ${{matrix.env}} bundle install
    
    - name: Run tests
      timeout-minutes: 5
      run: ${{matrix.env}} bundle exec rspec
